@company = your_company_name
@company = your_base_url

# @prompt username
# @prompt password

# Authentication
GET {{base_url}}/auth/{{company}}
Authorization: Basic {{username}}:{{password}}
Maconomy-Authentication: X-Cookie

###

@cookie = cookie_name

# Get instances
POST {{base_url}}/containers/{{company}}/timeregistration/instances
Authorization: X-Cookie {{cookie}}
Content-Type: application/vnd.deltek.maconomy.containers+json

{"panes": {}}

###

# Get all table rows
POST {{base_url}}/containers/{{company}}/timeregistration/instances/{{container_instance_id}}/data;any
Authorization: X-Cookie {{cookie}}
Maconomy-Concurrency-Control: {{concurrency_control}}

###

# Set data
POST {{base_url}}/containers/{{company}}/timeregistration/instances/{{container_instance_id}}/data/panes/table/0
Authorization: X-Cookie {{cookie}}
Maconomy-Concurrency-Control: {{concurrency_control}}
Content-Type: application/json
